In [7]:
import numpy as np

In [ ]:
ZERO = np.array([1, 0])
ONE  = np.array([0, 1])

### Spezial-Operator `SWAP`

Um die Methode `op` einfach zu halten, gibt man für einen Operator an, von welchem Bit an er wirkt. Natürlich passt das nicht immer. Manchmal arbeitet ein Operator bzw. ein Quantengatter beispielsweise auf zwei Qubits, die aber nicht hintereinander aufgereiht sind. Mit `SWAP` kann man zwei aufeinander folgende Qubits tauschen und sich so die Qubit-Folge geeignet arrangieren. Das ist zwar etwas mühsam, aber derzeit der Preis für eine so kurze `op`-Methode.  

In [8]:
SWAP = np.array([[1,0,0,0],
                 [0,0,1,0],
                 [0,1,0,0],
                 [0,0,0,1]])
SWAP

array([[1, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 1]])

### Quantengatter

Die implementierten Quantengatter orientieren sich an der [Liste der Quantengatter](https://de.wikipedia.org/wiki/Liste_der_Quantengatter) aus Wikipedia. Schaltungen werden mit diesen Quantengattern realisiert.

In [9]:
CNOT = np.array([[1,0,0,0],
                 [0,1,0,0],
                 [0,0,0,1],
                 [0,0,1,0]])
CNOT

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0]])

In [10]:
S = np.array([[1,0],
              [0,1j]])
S

array([[1.+0.j, 0.+0.j],
       [0.+0.j, 0.+1.j]])

In [11]:
inv_sqrt2 = 1 / 2**0.5 # 1 durch Wurzel aus Zwei
T = np.array([[1,0],
              [0, inv_sqrt2 + inv_sqrt2 * 1j]])
T

array([[1.        +0.j        , 0.        +0.j        ],
       [0.        +0.j        , 0.70710678+0.70710678j]])

In [12]:
H = inv_sqrt2 * np.array([[1, 1],
                          [1,-1]])
H

array([[ 0.70710678,  0.70710678],
       [ 0.70710678, -0.70710678]])

In [13]:
X = PAULIX = NOT = np.array([[0,1],
                             [1,0]])

In [14]:
Y = PAULIY = np.array([[0,0-1j],
                      [0+1j,0]])

In [15]:
Z = PAULIZ = np.array([[1,0],
                   [0,-1]])
PAULIZ

array([[ 1,  0],
       [ 0, -1]])

In [16]:
XROT = inv_sqrt2 * np.array([[1   ,0-1j],
                             [0-1j,   1]])
XROT

array([[0.70710678+0.j        , 0.        -0.70710678j],
       [0.        -0.70710678j, 0.70710678+0.j        ]])

In [17]:
YROT = inv_sqrt2 * np.array([[1,-1],[1,1]])
YROT

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [18]:
TOFFOLI = np.array([[1,0,0,0,0,0,0,0],
                    [0,1,0,0,0,0,0,0],
                    [0,0,1,0,0,0,0,0],
                    [0,0,0,1,0,0,0,0],
                    [0,0,0,0,1,0,0,0],
                    [0,0,0,0,0,1,0,0],
                    [0,0,0,0,0,0,0,1],
                    [0,0,0,0,0,0,1,0]])
TOFFOLI

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0]])